### Disciplina de Análise de Dados    
### Curso de Gestão de Dados
### Universidade Federal do Piauí
##### Prof. Arlino Magalhães
arlino@ufpi.edu.br | @arlino.magalhaes


# Operações vetoriais e matriciais com Numpy

Referência: Tadewald, Rodrigo. Python para Data Science e Machine Learning. Disponível em: Udemy, 2021. 
| Link da Udemy: https://www.udemy.com/course/python-para-data-science-e-machine-learning/

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [16]:
np.random.rand(10)*100

array([ 0.89576446, 78.66772337, 57.61919408, 51.25345549, 33.51314413,
       64.35836106, 78.30674006, 85.51291064, 29.37320078, 54.93781496])

In [18]:
np.random.rand(5,5)*100

array([[89.02677549, 83.56522428,  9.01347045, 70.38634945, 64.47901145],
       [66.09893077, 36.08053303, 91.51328416, 73.61582274, 16.02842332],
       [24.8424211 , 76.90113672,  6.01862309,  7.39274642, 71.80107115],
       [21.88127778, 71.75146435, 64.75103003,  9.22809576, 71.08669218],
       [90.14316694, 74.67749188, 50.59881368, 48.50879844,  9.4630808 ]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [19]:
np.random.randn(10)

array([ 0.60757524, -0.36158557,  0.8054575 , -1.26414639,  0.88009194,
        1.03037542,  0.21200734, -0.42674185, -0.28522279,  0.52259954])

In [20]:
np.random.randn(5,5)

array([[ 0.20893744,  1.5618483 , -0.17404707,  0.70146993, -0.5141642 ],
       [ 1.29224712, -0.80087307, -0.4409728 ,  1.24864859,  0.50755142],
       [-0.6402943 ,  0.82205359,  0.46562438,  0.5070075 ,  1.91323952],
       [ 0.21008127, -0.11711885, -0.6336326 , -0.6411277 , -0.83074297],
       [-1.12336593,  1.0412964 , -1.30522602, -1.49144511,  0.95975833]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [23]:
np.random.randint(1,100)

8

In [24]:
np.random.randint(1,100,10)

array([49,  5, 86, 28, 47, 77, 28,  3, 54, 59])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [25]:
array1 = np.arange(25)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
array2 = np.random.randint(0,50,10)
array2

array([ 2, 12, 24, 49,  8,  2, 45,  5, 24, 46])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [27]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
array1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [29]:
array2

array([ 2, 12, 24, 49,  8,  2, 45,  5, 24, 46])

In [30]:
array2.max()

49

In [31]:
array2.argmax()

3

In [32]:
array2.min()

2

In [33]:
array2.argmin()

0

## Shape

Shape é um atributo que os arrays têm (não um método):

In [34]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
# Vector
array1.shape

(25,)

In [36]:
array1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
array1.reshape(1,25).shape

(1, 25)

In [38]:
array1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
array1.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [40]:
array1.dtype

dtype('int32')